title: Alseny_Portofolio
logo: /images/photo.jpg
# description: texte pour logo
show_downloads: true
remote_theme: pages-themes/merlot@v0.2.0 #thelme: jekyll-theme-minimal
## photo ![](images/_K__2859.jpg)

#remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
